export const INC_QTY_CART = 'INC_QTY_CART';
export const DEC_QTY_CART = 'DEC_QTY_CART';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
